const PRODUCTS = [
{
"id": "15488281966",
"name": "\"CALL ME\" TEE IN ELECTRIC BLUE",
"price": 970.0,
"original_price": null,
"discount_pct": null,
"sold": 6.0,
"rating": null,
"reviews": 1.0,
"description": "Made with our custom lightweight cotton190gsmShoulder-to-shoulder tapeCustom embossed print on our signature oversized teeDouble-needle sleeves and bottom hemWorn-out feelTailored fitOversized body and sleevesCut and sew",
"category_top": "Men's Clothing",
"variations": [
"S",
"M",
"L",
"XXL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15488281966.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sda5d9f13d685466685ab368eb30db61aw.jpg"
},
{
"id": "4302632721",
"name": "BOXER BRIEF BUNDLE OF 3 (4 COLORWAYS)",
"price": 770.0,
"original_price": null,
"discount_pct": null,
"sold": 107.0,
"rating": null,
"reviews": 39.0,
"description": "Made with our custom cotton blendClassic FitBUNDLE OF 3",
"category_top": "Lingerie, Sleep, Lounge & Thermal Wear",
"variations": [
"SKIN TONE",
"STEALTH",
"OLIVE",
"BALTIC GREY",
"S",
"M",
"L",
"XL",
"XXL"
],
"url": "https://www.lazada.com.ph/products/pdp-i4302632721.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S9f8d58aa076c423a8fcbf62db02eabd6u.jpg"
},
{
"id": "15479429277",
"name": "\"THAI\" LOGO TEE IN (2 COLORWAYS)",
"price": 1088.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with our custom heavyweight cottonShoulder-to-shoulder tapeCustom embossed print on our signature oversized teeDouble-needle sleeves and bottom hemWorn-out feelTailored fitBoxy fitOversized body and sleevesCut and sew",
"category_top": "Men's Clothing",
"variations": [
"MUSTARD",
"STATIC PINK",
"M",
"L",
"XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15479429277.html",
"image": "https://img.lazcdn.com/g/p/a36831cc23ea31d6003b9ae0db0d27b3.jpg_200x200q80.jpg"
},
{
"id": "15530626872",
"name": "\"PEACE PAISLEY\" BANDANA SOCK IN (2 COLORWAYS)",
"price": 270.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": 5.0,
"reviews": 1.0,
"description": "Featuring our custom \"Peace Paisley\" printCOTTON 21%POLYESTER 66%ELASTIC 10%NYLON 2%SPANDEX 1%GREATNESS 100%",
"category_top": "Sports Shoes and Clothing",
"variations": [
"BLOOD RED",
"STONE GREY"
],
"url": "https://www.lazada.com.ph/products/pdp-i15530626872.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S37a7f4554a224ea5a6d32ad460bbbf67Q.jpg"
},
{
"id": "4297755607",
"name": "MN+LA SOCK - SINGLE (4 COLORWAYS)",
"price": 200.0,
"original_price": null,
"discount_pct": null,
"sold": 80.0,
"rating": 4.7,
"reviews": 28.0,
"description": "MN LA Guhit Regular Socks Street Nylon cotton Male",
"category_top": "Lingerie, Sleep, Lounge & Thermal Wear",
"variations": [
"White",
"CHERRY",
"ANTHRACITE",
"ELECTRIC BLUE",
"MOSS",
"CANARY",
"EARTH",
"CEMENT",
"EVERGREEN"
],
"url": "https://www.lazada.com.ph/products/pdp-i4297755607.html",
"image": "https://img.lazcdn.com/g/ff/kf/S6313e5afcadc470994b078f08ecebeccy.jpg_200x200q80.jpg"
},
{
"id": "4960805689",
"name": "OVERSIZED TEE (4 COLORWAYS)",
"price": 770.0,
"original_price": null,
"discount_pct": null,
"sold": 73.0,
"rating": 4.8,
"reviews": 23.0,
"description": "MN LA Regular Plain Casual Polyester",
"category_top": "Men's Clothing",
"variations": [
"GLACIER",
"NAVY",
"OLIVE",
"WHITE",
"SMALL",
"MEDIUM",
"LARGE",
"EXTRA-LARGE",
"2X-LARGE",
"3X-LARGE"
],
"url": "https://www.lazada.com.ph/products/pdp-i4960805689.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sfcf4f79fd3a14fb2a0753833a9e70bbcC.jpg"
},
{
"id": "15479890613",
"name": "\"AIR DANCER\" FEMME X MN+LA™ 5 PANEL HAT IN BUBBLE GUM PINK",
"price": 1070.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with cotton twillFront embroidery \"M\" Side embroidery \"Manila Meets Los Angeles\"Back embroidery minimalist logoVelcro closure",
"category_top": "Fashion Accessories",
"variations": [],
"url": "https://www.lazada.com.ph/products/pdp-i15479890613.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sae5f5f1f5cdc4ad0bd0f535a1cf3b20bp.jpg"
},
{
"id": "15479966477",
"name": "BOX TEE IN OLIVE",
"price": 770.0,
"original_price": null,
"discount_pct": null,
"sold": 6.0,
"rating": null,
"reviews": null,
"description": "Made with our custom heavyweight cotton220gsmRib knit collarShoulder-to-shoulder tapeDouble-needle sleeves and bottom hemReactive dyed for maximum printabilityTight crew neckWorn-out feelDropped shouldersOversizedVintage fitCut and sew",
"category_top": "Men's Clothing",
"variations": [
"S",
"L",
"XL",
"XXL",
"3XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15479966477.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S24bf071b78ef46d5b6bd8fbda5bdcf31i.jpg"
},
{
"id": "15480125275",
"name": "\"HITTER\" V3 5 PANEL HAT IN (5 COLORWAYS)",
"price": 1070.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with cotton twillFront embroidery \"M\" Side embroidery \"Manila Meets Los Angeles\"Back embroidery minimalist logoVelcro closure",
"category_top": "Sports Shoes and Clothing",
"variations": [
"OLIVE",
"ANTHRACITE",
"BUBBLE GUM PINK",
"STONE GREY",
"SAND"
],
"url": "https://www.lazada.com.ph/products/pdp-i15480125275.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sd5f95542adee4b50b9b101befc25b978O.jpg"
},
{
"id": "4387712679",
"name": "MN+LA™ PARFUM 50 ML (4 SCENTS)",
"price": 1070.0,
"original_price": null,
"discount_pct": null,
"sold": 106.0,
"rating": 4.8,
"reviews": 33.0,
"description": "MN+LA PARFUM 50 ML 7 SCENTS)",
"category_top": "Beauty",
"variations": [
"EVERGREEN",
"EMBER",
"KINDLE",
"WINTER"
],
"url": "https://www.lazada.com.ph/products/pdp-i4387712679.html",
"image": "https://img.lazcdn.com/g/ff/kf/Sf8ad099ae63f406392d2923d0ed7ba00J.jpg_200x200q80.jpg"
},
{
"id": "4711591240",
"name": "CLASSIC TEE (4 COLORWAYS)",
"price": 770.0,
"original_price": null,
"discount_pct": null,
"sold": 129.0,
"rating": 5.0,
"reviews": 42.0,
"description": "MN LA Graphic Street Cotton Blend",
"category_top": "Men's Clothing",
"variations": [
"ANTHRACITE",
"RUST",
"GLACIER",
"NAVY",
"SMALL",
"MEDIUM",
"LARGE",
"EXTRA-LARGE",
"2X-LARGE",
"3X-LARGE",
"4X-LARGE"
],
"url": "https://www.lazada.com.ph/products/pdp-i4711591240.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sb607740d8db14138b617a0118d4b1750R.jpg"
},
{
"id": "4701899303",
"name": "MN+LA™ BANDANA (3 COLORWAYS)",
"price": 370.0,
"original_price": null,
"discount_pct": null,
"sold": 150.0,
"rating": 5.0,
"reviews": 36.0,
"description": "MN LA Graphic cotton",
"category_top": "Fashion Accessories",
"variations": [
"MINT BUBBLE GUM PINK",
"GRAPHITE",
"WINTER WOODS"
],
"url": "https://www.lazada.com.ph/products/pdp-i4701899303.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S706e17d4f69c494f95c9d4df7be42ae2A.jpg"
},
{
"id": "15530133855",
"name": "\"OUTDOOR EXPLORATION\" SOCK IN WHITE",
"price": 270.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "COTTON 21%POLYESTER 66%ELASTIC 10%NYLON 2%SPANDEX 1%GREATNESS 100%",
"category_top": "Sports Shoes and Clothing",
"variations": [],
"url": "https://www.lazada.com.ph/products/pdp-i15530133855.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sa3306a84f6574df69c0c7a8e97806ae4Z.jpg"
},
{
"id": "15530714020",
"name": "TABI SOCKS IN (3 COLORWAYS)",
"price": 200.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": 5.0,
"reviews": 1.0,
"description": "COTTON 21%POLYESTER 66%ELASTIC 10%NYLON 2%SPANDEX 1%GREATNESS 100%",
"category_top": "Sports Shoes and Clothing",
"variations": [
"OAT",
"ANTHRACITE",
"CHARCOAL GREY"
],
"url": "https://www.lazada.com.ph/products/pdp-i15530714020.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S87486ddfce7347f5abebc3e1a21b040bm.jpg"
},
{
"id": "15542851530",
"name": "\"EDSA RACING CLUB\" TEE IN (2 COLORWAYS)",
"price": 1088.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with our custom heavyweight cotton220gsmRib knit collarShoulder-to-shoulder tapeDouble-needle sleeves and bottom hemReactive dyed for maximum printabilityTight crew neckWorn-out feelDropped shouldersOversizedBoxy fitCut and sew",
"category_top": "Men's Clothing",
"variations": [
"MUSTARD",
"APRICOT",
"S",
"M",
"L",
"XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15542851530.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sb6da7471bf184b029cb23fc6afb398134.jpg"
},
{
"id": "15492965994",
"name": "M'$ PAISLEY PAPER BAG",
"price": 50.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Buy M'$ PAISLEY PAPER BAG online at Lazada Philippines. Discount prices and promotional sale on all Costumes Props & Accessories. Free Shipping.",
"category_top": "Toys & Games",
"variations": [
"Small",
"Medium"
],
"url": "https://www.lazada.com.ph/products/pdp-i15492965994.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S9b550d445ac240eaabbe5aec9f984baa4.jpg"
},
{
"id": "15534344823",
"name": "MANDARIN SHORTS IN (3 COLORWAYS)",
"price": 1270.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with cotton panama fabricRelaxed fit2 side pockets2 welt back pockets with snapM button closureMN+LA rubber patch on back waistbandCut & sew",
"category_top": "Men's Clothing",
"variations": [
"SAND",
"OLIVE",
"ANTHRACITE",
"S",
"M",
"L",
"XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15534344823.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sa5f0bb301a1e405ebd5a26a540fb593fx.jpg"
},
{
"id": "15533830834",
"name": "\"HITTER\" V3 TOPSHELF LITE TEE IN RAVEN",
"price": 970.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with our custom lightweight cotton190gsmRib knit collarShoulder-to-shoulder tapeReactive dyed for maximum printabilityTight crew neckWorn out feelTailored fitOversized body and sleevesCut and sew",
"category_top": "Men's Clothing",
"variations": [
"S",
"M",
"L",
"XL",
"XXL",
"3XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15533830834.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sf66e54e370f64281a160056a98370dc99.jpg"
},
{
"id": "15530203114",
"name": "EXO™ ZIP TRUCKER JACKET IN WHEAT/HEATHER GREY",
"price": 2470.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with our custom French terry275gsm YKK double slider zipper2 side pockets Contrast threadTailored fitCut & sew",
"category_top": "Men's Clothing",
"variations": [
"S",
"M",
"L",
"XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15530203114.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sde61fb57673c41199097f80e31dabc1du.jpg"
},
{
"id": "4880271520",
"name": "SHINOBI CLOGS V2 (2 COLORWAYS)",
"price": 1470.0,
"original_price": null,
"discount_pct": null,
"sold": 7.0,
"rating": null,
"reviews": null,
"description": "SHINOBI CLOGS V2 2 COLORWAYS)",
"category_top": "Men's Shoes",
"variations": [
"HIMALAYAS",
"MULBERRY",
"6",
"7",
"8",
"9",
"10",
"11",
"12"
],
"url": "https://www.lazada.com.ph/products/pdp-i4880271520.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S2534ff51ce634679bffe1c6a2596178a7.jpg"
},
{
"id": "15500953473",
"name": "\"HITTER\" V3 CHOP CHOP LITE TEE IN ANTHRACITE",
"price": 970.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": 1.0,
"reviews": 1.0,
"description": "Made with our custom lightweight cotton190gsmRib knit collarShoulder-to-shoulder tapeReactive dyed for maximum printabilityTight crew neckWorn out feelTailored fitOversized body and sleevesDropped shoulderCut and sew",
"category_top": "Men's Clothing",
"variations": [
"S",
"M",
"L",
"XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15500953473.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S7fa82ccd11384b66a490b5828b602c53K.jpg"
},
{
"id": "15533820725",
"name": "\"HITTER\" V3 BOX LITE TEE IN ANTHRACITE",
"price": 970.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with our custom lightweight cotton190gsmShoulder-to-shoulder tapeReactive dyed for maximum printabilityTight crew neckWorn-out feelDropped shouldersBoxy fitCut and sew",
"category_top": "Men's Clothing",
"variations": [
"L",
"XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15533820725.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S19f0ccd346994b37b993f740539904b0A.jpg"
},
{
"id": "15481102696",
"name": "MANDARIN L/S SHIRT IN (2 COLORWAYS)",
"price": 1470.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with cotton linenBand collar Boxy fitCut & sew",
"category_top": "Men's Clothing",
"variations": [
"SLATE",
"WOOD",
"S",
"M",
"L",
"XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15481102696.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S0e328dd9a0404cfb8820b8d4299be423m.jpg"
},
{
"id": "15533797222",
"name": "\"HITTER\" V3 LOUNGE LITE TEE ANTHRACITE",
"price": 970.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with our custom lightweight cotton190gsmRib knit collarShoulder-to-shoulder tapeReactive dyed for maximum printabilityTight crew neckWorn out feelTailored slim fitCut and sew",
"category_top": "Men's Clothing",
"variations": [
"S",
"M",
"L",
"XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15533797222.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S6092c2f231e449638f555d01e5720291t.jpg"
},
{
"id": "15534384346",
"name": "PACE SHORTS IN (3 COLORWAYS)",
"price": 1270.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with cotton twillRelaxed fit2 side pockets2 back pocketsMN+LA rubber patch on back pocketCut & sew",
"category_top": "Men's Clothing",
"variations": [
"SAND",
"DUNE",
"MOSS",
"S",
"M",
"L",
"XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15534384346.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S11893b96477d407182b7ee6c722ed796s.jpg"
},
{
"id": "15500765284",
"name": "WAFFLE EXO™ TOPSHELF TEE IN ANTHRACITE/OLIVE",
"price": 870.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": 5.0,
"reviews": null,
"description": "Made with our custom heavyweight cotton220gsmRib knit collarShoulder-to-shoulder tapeDouble-needle sleeves and bottom hemReactive dyed for maximum printabilityTight crew neckWorn-out feelTailored fitOversized body and sleevesCut and sew",
"category_top": "Men's Clothing",
"variations": [
"M",
"L",
"XXL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15500765284.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sdcae3251b7294bc5ae358f83d7f8c6c55.jpg"
},
{
"id": "5087127022",
"name": "EXO™ MILITIA LONGSLEEVE TEE V3 IN OLIVE/TEAL",
"price": 1070.0,
"original_price": null,
"discount_pct": null,
"sold": 5.0,
"rating": 5.0,
"reviews": 1.0,
"description": "Made with our custom french terry Shoulder-to-shoulder tapeReactive dyed for maximum printabilityTight crew neckWorn out feelDropped shouldersOversizedVintage fitCut and sew",
"category_top": "Men's Clothing",
"variations": [
"SMALL",
"LARGE",
"EXTRA-LARGE"
],
"url": "https://www.lazada.com.ph/products/pdp-i5087127022.html",
"image": "https://img.lazcdn.com/g/p/55f687c14839894fcc341c79a45b0d3d.jpg_200x200q80.jpg"
},
{
"id": "15485109822",
"name": "\"HITTER\" V3 LOUNGE LITE TEE IN (2 COLORWAYS)",
"price": 970.0,
"original_price": null,
"discount_pct": null,
"sold": 6.0,
"rating": null,
"reviews": null,
"description": "Made with our custom lightweight cotton190gsmRib knit collarShoulder-to-shoulder tapeReactive dyed for maximum printabilityTight crew neckWorn out feelTailored slim fitCut and sew",
"category_top": "Men's Clothing",
"variations": [
"ANTHRACITE",
"OAT",
"S",
"M",
"L",
"XL",
"XXL",
"3XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15485109822.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S863ad50f0f6b412eb313ddcf9ceb52b8m.jpg"
},
{
"id": "15497248983",
"name": "BOX TEE IN SHADOW PURPLE",
"price": 770.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": 5.0,
"reviews": 1.0,
"description": "Made with our custom heavyweight cotton220gsmRib knit collarShoulder-to-shoulder tapeDouble-needle sleeves and bottom hemReactive dyed for maximum printabilityTight crew neckWorn out feelDropped shouldersOversizedVintage fitCut and sew",
"category_top": "Men's Clothing",
"variations": [
"XL",
"XXL",
"3XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15497248983.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sb6a721b0c6eb4c04915dc9a2ddbf4bb1E.jpg"
},
{
"id": "15479926396",
"name": "\"HITTER\" V3 6 PANEL HAT IN (3 COLORWAYS)",
"price": 970.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with cotton twillEmbroidered \"M” logoContrast stitchingMesh rear panelsAdjustable snapback",
"category_top": "Sports Shoes and Clothing",
"variations": [
"ANTHRACITE",
"BLACK/WHITE",
"BLACK/OLIVE"
],
"url": "https://www.lazada.com.ph/products/pdp-i15479926396.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S5cd69f4a4d97468fbec3b4ed815b6a64h.jpg"
},
{
"id": "15492997815",
"name": "LOUNGE TEE IN ( 5 COLORWAYS)",
"price": 770.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with our custom heavyweight cotton220gsmRib knit collarShoulder-to-shoulder tapeDouble-needle sleeves and bottom hemReactive dyed for maximum printabilityTight crew neckWorn out feelTailored slim fitCut and sew",
"category_top": "Men's Clothing",
"variations": [
"ANTHRACITE",
"WOOD",
"WHITE",
"CAVIAR",
"CHARCOAL GREY",
"XS",
"S",
"M",
"L",
"XL",
"XXL",
"3XL",
"4XL"
],
"url": "https://www.lazada.com.ph/products/pdp-i15492997815.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S98a611189cb6467da9c7e6740ed4d0094.jpg"
},
{
"id": "15479904616",
"name": "\"AIR OUT\" TRUCKER HAT IN ANTHRACITE BY WSH X MN+LA™",
"price": 970.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with cotton twillContrast stitchingMesh rear panelsAdjustable snapback",
"category_top": "Sports Shoes and Clothing",
"variations": [],
"url": "https://www.lazada.com.ph/products/pdp-i15479904616.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Sf56aa863b8ab49ddbb5297a999d50d518.jpg"
},
{
"id": "15479902769",
"name": "\"QI\" TRUCKER HAT BY WSH x MN+LA™ IN (2 COLORWAYS)",
"price": 970.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "*A Witness Surreal Hypnosis & Manila Meets Los Angeles Collaboration*Made with cotton twillMesh rear panelsEmbroidered logoAdjustable snapback",
"category_top": "Sports Shoes and Clothing",
"variations": [
"ANTHRACITE",
"EMERALD"
],
"url": "https://www.lazada.com.ph/products/pdp-i15479902769.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Saa5bb034a18c40c9bc21efeafc86ecadv.jpg"
},
{
"id": "15479156860",
"name": "\"BALANCE\" 6 PANEL HAT IN (2 COLORWAYS)",
"price": 1270.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with cotton twill Front embroidery Back embroidery minimalist logoVelcro closure",
"category_top": "Fashion Accessories",
"variations": [
"ANTHRACITE",
"Olive"
],
"url": "https://www.lazada.com.ph/products/pdp-i15479156860.html",
"image": "https://img.lazcdn.com/g/p/6fc2a25e3597e01cd4d8cc23f77a85cf.jpg_200x200q80.jpg"
},
{
"id": "15480151027",
"name": "\"COLLIDE\" 5 PANEL HAT IN ANTHRACITE",
"price": 1270.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with cotton twillFront embroidery Back embroidery minimalist logoVelcro closure",
"category_top": "Sports Shoes and Clothing",
"variations": [],
"url": "https://www.lazada.com.ph/products/pdp-i15480151027.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S8aeb2da900d44677ab7a7934137320b1q.jpg"
},
{
"id": "5026197731",
"name": "M+ HIKE PANTS IN WHEAT",
"price": 1970.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": 5.0,
"reviews": 2.0,
"description": "MN LA Plain Wide Leg Natural Waist Street Cotton Blend",
"category_top": "Men's Clothing",
"variations": [
"LARGE",
"EXTRA-LARGE"
],
"url": "https://www.lazada.com.ph/products/pdp-i5026197731.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S2ed10302b626463787bc8fe1d5962f84f.jpg"
},
{
"id": "15479300020",
"name": "\"HITTER\" V3 6 PANEL HAT IN (10 COLORWAYS)",
"price": 970.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with cotton twill Front embroidery \"M\" Back embroidery minimalist logoVelcro closure",
"category_top": "Sports Shoes and Clothing",
"variations": [
"WHITE/NAVY",
"FLAMINGO",
"BUBBLE GUM PINK",
"SAND",
"DUNE",
"CHARCOAL /RARRI RED",
"WOOD",
"OLIVE/CANARY",
"ANTHRACITE/OLIVE",
"OLIVE"
],
"url": "https://www.lazada.com.ph/products/pdp-i15479300020.html",
"image": "https://img.lazcdn.com/g/p/cf08b40df288bcc67fe95f61769880b7.jpg_200x200q80.jpg"
},
{
"id": "15480061706",
"name": "\"COPACABANA\" TRUCKER HAT IN (3 COLORWAYS)",
"price": 1270.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with cotton twillMesh rear panelsAdjustable snapback",
"category_top": "Sports Shoes and Clothing",
"variations": [
"CYPRESS TEAL",
"GRANITE",
"LIMESTONE"
],
"url": "https://www.lazada.com.ph/products/pdp-i15480061706.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S225dad8d5e6d4e45b6af1bd779350336u.jpg"
},
{
"id": "15481605184",
"name": "ONYX HERRINGBONE CHAIN NECKLACE",
"price": 1370.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Dark onyx toneFlatWide chainStatement piece",
"category_top": "Fashion Accessories",
"variations": [],
"url": "https://www.lazada.com.ph/products/pdp-i15481605184.html",
"image": "https://img.lazcdn.com/g/p/b94f1f9524881ef22eb2bce968dfc7d6.jpg_200x200q80.jpg"
},
{
"id": "15481668127",
"name": "CHAIN RING",
"price": 1170.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Stainless steel*Free 1pc Sac Cord in a randomly selected color.",
"category_top": "Fashion Accessories",
"variations": [
"16",
"17",
"18",
"19",
"20",
"21",
"22"
],
"url": "https://www.lazada.com.ph/products/pdp-i15481668127.html",
"image": "https://img.lazcdn.com/g/p/6b676a34ad01ac25fea3228bb49ebea1.jpg_200x200q80.jpg"
},
{
"id": "15481670192",
"name": "CUBE CHAIN NECKLACE",
"price": 1370.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Silver-toneSquare link chainSleek and modern styleLightweight and versatile Gold-toneSquare link chainElegant and timelessLightwear for daily wear",
"category_top": "Fashion Accessories",
"variations": [
"Gold",
"Silver"
],
"url": "https://www.lazada.com.ph/products/pdp-i15481670192.html",
"image": "https://img.lazcdn.com/g/p/89581c4e65952124677e6584de609dca.jpg_200x200q80.jpg"
},
{
"id": "15481521707",
"name": "LUCENT LINK CHAIN NECKLACE",
"price": 1370.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Silver-toneRectangular clip-style linksTrendy and bold lookStatement chain for layeringEveryday accessory",
"category_top": "Fashion Accessories",
"variations": [],
"url": "https://www.lazada.com.ph/products/pdp-i15481521707.html",
"image": "https://img.lazcdn.com/g/p/ba9a0c95427d8602033a525d6467c8b6.jpg_200x200q80.jpg"
},
{
"id": "5087577358",
"name": "MN+LA BRACELETS",
"price": 870.0,
"original_price": null,
"discount_pct": null,
"sold": 13.0,
"rating": 5.0,
"reviews": 6.0,
"description": "MN LA Crystal Male",
"category_top": "Fashion Accessories",
"variations": [
"ONYX",
"GROW A SPINE V2",
"FLOW",
"GLEAMSTONE"
],
"url": "https://www.lazada.com.ph/products/pdp-i5087577358.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/Se1ee8ee499cc47a99298bc10224d426an.jpg"
},
{
"id": "15481503505",
"name": "BALANCE V2 RING",
"price": 1170.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Sterling silverClassic signet shapeYin yang ring*Free 1pc Sac Cord in a randomly selected color.",
"category_top": "Fashion Accessories",
"variations": [
"7",
"8",
"9",
"10"
],
"url": "https://www.lazada.com.ph/products/pdp-i15481503505.html",
"image": "https://img.lazcdn.com/g/p/89c4162ffd00f8e785e2a438e1a3b036.jpg_200x200q80.jpg"
},
{
"id": "15530638015",
"name": "\"PORTAL HOUSE 33\" HOODIE IN (2 COLORWAYS)",
"price": 3333.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with our custom brushed terry 400gsmClassic hoodSide pocketsDropped shouldersCut & sew",
"category_top": "Men's Clothing",
"variations": [
"M",
"L",
"XL",
"OAT",
"STATIC PINK"
],
"url": "https://www.lazada.com.ph/products/pdp-i15530638015.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S5e81cf68e6dc489bb7a6f5edd54547a7d.jpg"
},
{
"id": "5083040253",
"name": "FIELD TRAINERS IN DUNE",
"price": 4570.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "MN+LA Field Trainers in PU Leather offer comfort and style for men's sports activities. Featuring mesh and foam construction, these sneakers provide breathability and support, with multiple size options and durable rubber soles. - Lazada",
"category_top": "Men's Shoes",
"variations": [
"6",
"7",
"8",
"9",
"10",
"11"
],
"url": "https://www.lazada.com.ph/products/pdp-i5083040253.html",
"image": "https://img.lazcdn.com/g/p/332b908b852f3a2bbbb698d92deebd71.png_200x200q80.png"
},
{
"id": "15481664106",
"name": "PLATINUM RING",
"price": 1170.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Stainless steel *Free 1pc Sac Cord in a randomly selected color.",
"category_top": "Fashion Accessories",
"variations": [
"16",
"17",
"18",
"19",
"20"
],
"url": "https://www.lazada.com.ph/products/pdp-i15481664106.html",
"image": "https://img.lazcdn.com/g/p/a97fd114b783fe77eadabaac19343757.jpg_200x200q80.jpg"
},
{
"id": "15481614446",
"name": "ANTHRACITE RING",
"price": 1170.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Black-coated metalSolid square faceClassic signet shapeSemi-gloss finish*Free 1pc Sac Cord in a randomly selected color.",
"category_top": "Fashion Accessories",
"variations": [
"7",
"8",
"9",
"10",
"11",
"12"
],
"url": "https://www.lazada.com.ph/products/pdp-i15481614446.html",
"image": "https://img.lazcdn.com/g/p/0f5026408bf05bf3734a5409f2f7ab6d.jpg_200x200q80.jpg"
},
{
"id": "15481509588",
"name": "BALANCE RING",
"price": 1170.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Stainless steel*Free 1pc Sac Cord in a randomly selected color.",
"category_top": "Fashion Accessories",
"variations": [
"7",
"8",
"9",
"10",
"11"
],
"url": "https://www.lazada.com.ph/products/pdp-i15481509588.html",
"image": "https://img.lazcdn.com/g/p/c3d1ff44c53e83a5b624bcebdd332f2d.jpg_200x200q80.jpg"
},
{
"id": "15481587218",
"name": "SNAKE GOLD CHAIN NECKLACE",
"price": 1370.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Gold-toneSleek and elegantLightweight Daily wear",
"category_top": "Fashion Accessories",
"variations": [],
"url": "https://www.lazada.com.ph/products/pdp-i15481587218.html",
"image": "https://img.lazcdn.com/g/p/d05a215651434a1033a36d42561c6053.jpg_200x200q80.jpg"
},
{
"id": "15479896713",
"name": "AFTERMARKET x MN+LA™ 5 PANEL HAT IN ANTHRACITE",
"price": 1070.0,
"original_price": null,
"discount_pct": null,
"sold": null,
"rating": null,
"reviews": null,
"description": "Made with cotton twillFront embroideryBack embroideryVelcro closure",
"category_top": "Pet Supplies",
"variations": [],
"url": "https://www.lazada.com.ph/products/pdp-i15479896713.html",
"image": "https://filebroker-cdn.lazada.com.ph/kf/S5c9b9caaf94b4783a055b9d3ddfda64fr.jpg"
}
];